CoreBookUI/Models/ErrorViewModel.cs
using System;

namespace CoreBookUI.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CoreBookUI/Controllers/BookController.cs
using Business.Abstract;
using Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreBookUI.Controllers
{
    public class BookController : Controller
    {
        private IBookService _bookService;
        public BookController(IBookService _bookService)
        {
            this._bookService = _bookService;
        }
        [Authorize]
        public IActionResult Index()
        {
            var books = _bookService.GetAllBook().ToList();
            return View(books);
        }
        [HttpGet]
        public IActionResult NewBook()
        {
            List<SelectListItem> dgr = _bookService.AddBook();
            ViewBag.s = dgr;
            return View();
        }
        [HttpPost]
        public IActionResult NewBook(Book b)
        {
            _bookService.AddBook(b);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _bookService.DeleteBook(id);
            return RedirectToAction("Index");
        }
        public IActionResult GetById(int id)
        {
            List<SelectListItem> dgr = _bookService.AddBook();
            ViewBag.s = dgr;
            var deger = _bookService.GetByIdBook(id);
            return View(deger);
        }
        public IActionResult Update(Book b)
        {
            _bookService.UpdateBook(b);
            return RedirectToAction("Index");
        }
    }
}

CoreBookUI/Controllers/GenreController.cs
using Business.Abstract;
using Entity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoreBookUI.Controllers
{
    public class GenreController : Controller
    {
        private IBookService _bookService;
        public GenreController(IBookService _bookService)
        {
            this._bookService = _bookService;
        }
        public IActionResult Index()
        {
            List<Genre> getGenre = _bookService.GetAllGenre();
            return View(getGenre);
        }
        [HttpGet]
        public IActionResult NewGenre()
        {
            return View();
        }
        [HttpPost]
        public IActionResult NewGenre(Genre g)
        {
            _bookService.Add(g);
            return RedirectToAction("Index");
        }
        public IActionResult Delete(int id)
        {
            _bookService.Delete(id);
            return RedirectToAction("Index");
        }
        public IActionResult GetById(int id)
        {
            var deger = _bookService.GetById(id);
            return View(deger);
        }
        public IActionResult Update(Genre g)
        {
            _bookService.Update(g);
            return RedirectToAction("Index");
        }
        public IActionResult Detail(int id)
        {
            var d = _bookService.Edit(id);
            ViewBag.send = d;
            var dgr = _bookService.Detail(id);
            return View(dgr);
        }
    }
}

CoreBookUI/Controllers/HomeController.cs
using Business.Abstract;
using CoreBookUI.Models;
using Entity.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace CoreBookUI.Controllers
{
    public class HomeController : Controller
    {
        private IBookService _bookService;
        public HomeController(IBookService _bookService)
        {
            this._bookService = _bookService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult About()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }
        public async Task<IActionResult> Login(Admin a)
        {
           var info= _bookService.Login(a);
            if (info != null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name,a.Username)
                };
                var useridentity = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(useridentity);
                await HttpContext.SignInAsync(principal);
                return RedirectToAction("Index", "Book");
            }
            return View();
        }
    }
}

CoreBookUI/Views/Book/GetById.cshtml
@model Entity.Book
@{
    ViewData["Title"] = "GetById";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

@using (Html.BeginForm("Update", "Book", FormMethod.Post))
{
    <b>Book ID</b>
    @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
    <br />
    <b>Book name</b>
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    <b>Author</b>
    @Html.TextBoxFor(x => x.Author, new { @class = "form-control" })
    <br />
    <b>Date</b>
    @*@Html.TextBoxFor(x => x.Date, new { @type = "date",@class="form-control" })*@
    @Html.TextBoxFor(m => m.Date, "{0:d MMM yyyy}", new { @class = "form-control" })
   
    <br />
    <b>Page</b>
    @Html.TextBoxFor(x => x.Page, new { @class = "form-control" })
    <br />
    <b>Genre</b>
    @Html.DropDownListFor(x => x.Genre.ID, (List<SelectListItem>)ViewBag.s, new { @class = "form-control" })
    <br />

    <button class="btn btn-info" style="background-color:#c64343">Update</button>
}

CoreBookUI/Views/Book/Index.cshtml
@model List<Entity.Book>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<h2>Books</h2>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Author</th>
            <th>Page</th>
            <th>Date</th>
            <th>GenreId</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.ID</td>
                <td>@x.Name</td>
                <td>@x.Author</td>
                <td>@x.Page</td>
                <td>@x.Date</td>
                <td>@x.Genre.Name</td>
                <td><a href="/Book/GetById/@x.ID" class="btn btn-success">Update</a></td>
                <td><a href="/Book/Delete/@x.ID" class="btn btn-danger">Delete</a></td>

            </tr>
        }
    </tbody>
</table>
<a href="/Book/NewBook/" class="btn btn-primary">New Book</a>

CoreBookUI/Views/Book/NewBook.cshtml
@model Entity.Book
@{
    ViewData["Title"] = "NewBook";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<form class="form-group" method="post">
    <b>Book name</b>
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    <b>Author</b>
    @Html.TextBoxFor(x => x.Author, new { @class = "form-control" })
    <br />
    <b>Number of page</b>
    @Html.TextBoxFor(x => x.Page, new { @class = "form-control" })
    <br />
    <b>Date</b>
    @Html.TextBoxFor(x => x.Date, "{0:d MMM yyyy}", new { @class = "form-control" })
    <br />
    <b>Genre</b>
    @Html.DropDownListFor(x=>x.Genre.ID,(List<SelectListItem>)ViewBag.s, new { @class="form-control"})
    <br />
    <button class="btn btn-info">Add</button>
</form>

CoreBookUI/Views/Genre/Detail.cshtml
@model List<Entity.Book>
@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}
<br />
<h2>@ViewBag.send</h2>
<br />
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Author</th>
            <th>Page</th>
            <th>Date</th>
            <th>GenreId</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in Model)
        {
            <tr>
                <td>@x.ID</td>
                <td>@x.Name</td>
                <td>@x.Author</td>
                <td>@x.Page</td>
                <td>@x.Date</td>
                <td>@x.Genre.Name</td>
            </tr>
        }
    </tbody>
</table>

CoreBookUI/Views/Genre/GetById.cshtml
@model Entity.Genre
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

@using (Html.BeginForm("Update", "Genre", FormMethod.Post))
{
    <b>Genre ID</b>
    @Html.TextBoxFor(x => x.ID, new { @class = "form-control" })
    <br />
    <b>Genre</b>
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    <button class="btn btn-info" style="background-color:#c64343">Update</button>
}

CoreBookUI/Views/Genre/Index.cshtml
@model List<Entity.Genre>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<h1>Genres</h1>

<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Update</th>
            <th>Delete</th>
            <th>Details</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var x in Model)
            {
                <tr>
                    <td>@x.ID</td>
                    <td>@x.Name</td>
                    <td><a href="/Genre/GetById/@x.ID" class="btn btn-success">Update</a></td>
                    <td><a href="/Genre/Delete/@x.ID" class="btn btn-danger">Delete</a></td>
                    <td><a href="/Genre/Detail/@x.ID" class="btn btn-outline-primary" style="background-color:#ffffff"  >Details</a></td>

                </tr>
            }
    </tbody>
</table>
<a href="/Genre/NewGenre/" class="btn btn-primary">New Genre</a>

CoreBookUI/Views/Genre/NewGenre.cshtml
@model Entity.Genre
@{
    ViewData["Title"] = "NewGenre";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<form class="form-group" method="post">
    <b>Genre</b>
    @Html.TextBoxFor(x=>x.Name, new { @class="form-control"})
    <br />
    <button class="btn btn-info">Add</button>
</form>

CoreBookUI/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<br />
<div>This is a library project. You can add, delete, update the books and their genres and list the books of the genres in detail</div>

CoreBookUI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CoreBookUI/Views/Home/Login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <title>Blend Login Form Flat Responsive Widget Template :: w3layouts</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Blend  Login Form template Responsive, Login form web template,Flat Pricing tables,Flat Drop downs  Sign up Web Templates, Flat Web Templates, Login sign up Responsive web template, SmartPhone Compatible web template, free WebDesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!-- Custom Theme files -->
    <link href="~/web/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/web/css/font-awesome.css" rel="stylesheet"> <!-- Font-Awesome-Icons-CSS -->
    <!-- //Custom Theme files -->
    <!-- web font -->
    <link href="//fonts.googleapis.com/css?family=Vollkorn+SC:400,600,700,900&amp;subset=cyrillic,cyrillic-ext,latin-ext,vietnamese" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Acme" rel="stylesheet">
    <!-- //web font -->
</head>
<body>
    <!-- main -->
    <div class="main">
        <h1> Login Form</h1>
        <div class="main-w3lsrow">
            <!-- login form -->
            <div class="login-form login-form-left">
                <div class="agile-row">
                    <h2>Login Here</h2>
                    <div class="login-agileits-top">
                        <form action="#" method="post">
                            <p>User Name </p>
                            <input type="text" class="name" name="Username" required="" />
                            <p>Password</p>
                            <input type="password" class="password" name="Password" required="" />
                            <label class="anim">
                                <input type="checkbox" class="checkbox">
                                <span> Remember me ?</span>
                            </label>
                            <input type="submit" value="Login">
                        </form>
                    </div>
                    <div class="login-agileits-bottom">
                        <h6><a href="#">Forgot password?</a></h6>
                    </div>
                    <div class="login-agileits-bottom1">
                        <h3>(or)</h3>

                    </div>
                    <div class="social_icons agileinfo">
                        <ul class="top-links">
                            <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
        <!-- copyright -->
        <div class="copyright">
            <p> © 2018 Blend  Login Form. All rights reserved | Design by <a href="http://w3layouts.com/" target="_blank">W3layouts</a></p>
        </div>
        <!-- //copyright -->
    </div>
    <!-- //main -->
</body>
</html>

CoreBookUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoreBookUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CoreBookUI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CoreBookUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

CoreBookUI/Views/Shared/_TestLayout.cshtml
<!DOCTYPE html>
<html>
<title>Library</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link href="~/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
<body>

    <!-- Sidebar -->
    <div class="w3-sidebar w3-light-grey w3-bar-block" style="width:15%">
        <h3 class="w3-bar-item">Menu</h3>
        <a href="/Genre/Index/" class="w3-bar-item w3-button">Genres</a>
        <a href="/Book/Index/" class="w3-bar-item w3-button">Books</a>
        <a href="/Home/About/" class="w3-bar-item w3-button">About</a>
    </div>

    <!-- Page Content -->
    <div style="margin-left:15%">

        <div class="w3-container w3-teal">
            <h1>Library</h1>
        </div>


        <div class="w3-container">
            @RenderBody()
        </div>

    </div>

</body>
</html>